Add xml-test-run command documentation
SatelliteQE/betelgeuse pull request #88
Opened 2016-10-10 20:21 UTC by elyezer

Add a chapter to the documentation with more information about how to run the
xml-test-run command.

2016-10-10 20:35 UTC, sthirugn commented on docs/index.rst
> +the information the Test Run XML importer needs.
Please break this section in to bullets.  Something like:

```
It takes the following inputs:
* a Valid xUnit XML file
* a Python test suite where test case IDs can be found

It generates a resulting XML file with all the information necessary for the Test Run XML importer.
```

2016-10-10 20:39 UTC, sthirugn requested changes

2016-10-10 20:39 UTC, sthirugn commented on docs/index.rst
> +already exists).
Please break this section in to different bullet items

2016-10-10 20:39 UTC, sthirugn commented on docs/index.rst
> +handled by Betelgeuse).
Add a note section for this paragraph

2016-10-10 20:39 UTC, sthirugn commented on docs/index.rst
> +
Move these two statements starting with `Make sure to pass` to a `warning` section

2016-10-11 15:05 UTC, elyezer commented
Comments addressed

2016-10-11 15:08 UTC, elyezer commented
Since I am touching the documentation I decided to add a second commit to update the default token prefix from `@` to `:` on docs.

2016-10-11 15:11 UTC, sthirugn commented
ACK

2016-10-11 15:12 UTC, sthirugn approved these changes

2016-10-11 15:12 UTC, merged